apiVersion: v1
kind: Service
metadata:
  name: cloudrive-svc
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: cloudrive
spec:
  ports:
  - name: '3000'
    port: 3000
    targetPort: 3000
  selector:
    app: cloudrive
  type: ClusterIP